insert into user values (1, 'Tom', 'Tom@tom.com')
insert into user values (2, 'John', 'John@john.com')
insert into user values (3, 'Adam', 'Adam@adam.com')

insert into category values (1, 'Apperal')
insert into category values (2, 'Books & Stationary')
insert into category values (3, 'Commute')
insert into category values (4, 'Dinning Out')
insert into category values (5, 'Essential Billings')
insert into category values (6, 'Fitness')
insert into category values (7, 'Grocery')
insert into category values (8, 'Healthcare')
insert into category values (9, 'Hobbies')
insert into category values (10, 'Travel')
insert into category values (11, 'Other')

insert into expense values (100,'New York Trip','2019-06-16','New York',10,1)
insert into expense values (101,'Uber','2019-06-15','Los Angeles',3,2)
insert into expense values(102,'Grand Canyon Trip With Family','2019-06-15','Arizona',10,3)